#
# This source file is part of the StanfordBDHG Template Application project
#
# SPDX-FileCopyrightText: 2023 Stanford University
#
# SPDX-License-Identifier: MIT
#

project: HealthyLLM.xcodeproj
schemes:
- HealthyLLM
report_exclude:
- "**/GeneratedOpenAIClient/OpenAPIGenerator/GeneratedSources/**"