version = 1

[[annotations]]
path = ["HealthyLLM.xcodeproj/**", "HealthyLLM/Supporting Files/**", "HealthyLLM/Supporting Files/**"]
SPDX-FileCopyrightText = "2025 Stanford University and the project authors (see CONTRIBUTORS.md)"
SPDX-License-Identifier = "MIT"