version = 1

[[annotations]]
path = [
    "HealthyLLM.xcodeproj/**",
    "HealthyLLM/Supporting Files/**",
    "HealthyLLM.xctestplan",
    "Analysis/**",
    "HealthyLLMStudy/Supporting Files/**",
]
SPDX-FileCopyrightText = "2026 Stanford University and the project authors (see CONTRIBUTORS.md)"
SPDX-License-Identifier = "MIT"